//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.1
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.1.
// 
#pragma warning disable 1591

namespace WindowsFormsApplication1.ServicioWindows {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="WebServiceSoap", Namespace="http://tempuri.org/")]
    public partial class WebService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SerializarClienteOperationCompleted;
        
        private System.Threading.SendOrPostCallback SerializarAdminOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaAeropuertoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarAeropuertoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAeropuertoOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaAeropuertoOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarAeroOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarAeropuertoCiudadPartidaOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaLineasOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarLineasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarLineasOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaLineasOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarLineasOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaVuelosOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarVueloOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListarVueloOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaVueloOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarVueloOperationCompleted;
        
        private System.Threading.SendOrPostCallback ReservaOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListAeroPartidadosOperationCompleted;
        
        private System.Threading.SendOrPostCallback LogueoOperationCompleted;
        
        private System.Threading.SendOrPostCallback AltaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BajaUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ModificarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback BuscarUsuarioOperationCompleted;
        
        private System.Threading.SendOrPostCallback ListavuelosxmlOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public WebService() {
            this.Url = global::WindowsFormsApplication1.Properties.Settings.Default.WindowsFormsApplication1_ServicioWindows_WebService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SerializarClienteCompletedEventHandler SerializarClienteCompleted;
        
        /// <remarks/>
        public event SerializarAdminCompletedEventHandler SerializarAdminCompleted;
        
        /// <remarks/>
        public event AltaAeropuertoCompletedEventHandler AltaAeropuertoCompleted;
        
        /// <remarks/>
        public event BuscarAeropuertoCompletedEventHandler BuscarAeropuertoCompleted;
        
        /// <remarks/>
        public event ListarAeropuertoCompletedEventHandler ListarAeropuertoCompleted;
        
        /// <remarks/>
        public event BajaAeropuertoCompletedEventHandler BajaAeropuertoCompleted;
        
        /// <remarks/>
        public event ModificarAeroCompletedEventHandler ModificarAeroCompleted;
        
        /// <remarks/>
        public event ListarAeropuertoCiudadPartidaCompletedEventHandler ListarAeropuertoCiudadPartidaCompleted;
        
        /// <remarks/>
        public event AltaLineasCompletedEventHandler AltaLineasCompleted;
        
        /// <remarks/>
        public event BuscarLineasCompletedEventHandler BuscarLineasCompleted;
        
        /// <remarks/>
        public event ListarLineasCompletedEventHandler ListarLineasCompleted;
        
        /// <remarks/>
        public event BajaLineasCompletedEventHandler BajaLineasCompleted;
        
        /// <remarks/>
        public event ModificarLineasCompletedEventHandler ModificarLineasCompleted;
        
        /// <remarks/>
        public event AltaVuelosCompletedEventHandler AltaVuelosCompleted;
        
        /// <remarks/>
        public event BuscarVueloCompletedEventHandler BuscarVueloCompleted;
        
        /// <remarks/>
        public event ListarVueloCompletedEventHandler ListarVueloCompleted;
        
        /// <remarks/>
        public event BajaVueloCompletedEventHandler BajaVueloCompleted;
        
        /// <remarks/>
        public event ModificarVueloCompletedEventHandler ModificarVueloCompleted;
        
        /// <remarks/>
        public event ReservaCompletedEventHandler ReservaCompleted;
        
        /// <remarks/>
        public event ListAeroPartidadosCompletedEventHandler ListAeroPartidadosCompleted;
        
        /// <remarks/>
        public event LogueoCompletedEventHandler LogueoCompleted;
        
        /// <remarks/>
        public event AltaUsuarioCompletedEventHandler AltaUsuarioCompleted;
        
        /// <remarks/>
        public event BajaUsuarioCompletedEventHandler BajaUsuarioCompleted;
        
        /// <remarks/>
        public event ModificarUsuarioCompletedEventHandler ModificarUsuarioCompleted;
        
        /// <remarks/>
        public event BuscarUsuarioCompletedEventHandler BuscarUsuarioCompleted;
        
        /// <remarks/>
        public event ListavuelosxmlCompletedEventHandler ListavuelosxmlCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SerializarCliente", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Cliente SerializarCliente(Cliente cliente) {
            object[] results = this.Invoke("SerializarCliente", new object[] {
                        cliente});
            return ((Cliente)(results[0]));
        }
        
        /// <remarks/>
        public void SerializarClienteAsync(Cliente cliente) {
            this.SerializarClienteAsync(cliente, null);
        }
        
        /// <remarks/>
        public void SerializarClienteAsync(Cliente cliente, object userState) {
            if ((this.SerializarClienteOperationCompleted == null)) {
                this.SerializarClienteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSerializarClienteOperationCompleted);
            }
            this.InvokeAsync("SerializarCliente", new object[] {
                        cliente}, this.SerializarClienteOperationCompleted, userState);
        }
        
        private void OnSerializarClienteOperationCompleted(object arg) {
            if ((this.SerializarClienteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SerializarClienteCompleted(this, new SerializarClienteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/SerializarAdmin", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Administrador SerializarAdmin(Administrador admin) {
            object[] results = this.Invoke("SerializarAdmin", new object[] {
                        admin});
            return ((Administrador)(results[0]));
        }
        
        /// <remarks/>
        public void SerializarAdminAsync(Administrador admin) {
            this.SerializarAdminAsync(admin, null);
        }
        
        /// <remarks/>
        public void SerializarAdminAsync(Administrador admin, object userState) {
            if ((this.SerializarAdminOperationCompleted == null)) {
                this.SerializarAdminOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSerializarAdminOperationCompleted);
            }
            this.InvokeAsync("SerializarAdmin", new object[] {
                        admin}, this.SerializarAdminOperationCompleted, userState);
        }
        
        private void OnSerializarAdminOperationCompleted(object arg) {
            if ((this.SerializarAdminCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SerializarAdminCompleted(this, new SerializarAdminCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaAeropuerto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaAeropuerto(Aeropuerto aero) {
            this.Invoke("AltaAeropuerto", new object[] {
                        aero});
        }
        
        /// <remarks/>
        public void AltaAeropuertoAsync(Aeropuerto aero) {
            this.AltaAeropuertoAsync(aero, null);
        }
        
        /// <remarks/>
        public void AltaAeropuertoAsync(Aeropuerto aero, object userState) {
            if ((this.AltaAeropuertoOperationCompleted == null)) {
                this.AltaAeropuertoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaAeropuertoOperationCompleted);
            }
            this.InvokeAsync("AltaAeropuerto", new object[] {
                        aero}, this.AltaAeropuertoOperationCompleted, userState);
        }
        
        private void OnAltaAeropuertoOperationCompleted(object arg) {
            if ((this.AltaAeropuertoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaAeropuertoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarAeropuerto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Aeropuerto BuscarAeropuerto(string codigo) {
            object[] results = this.Invoke("BuscarAeropuerto", new object[] {
                        codigo});
            return ((Aeropuerto)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarAeropuertoAsync(string codigo) {
            this.BuscarAeropuertoAsync(codigo, null);
        }
        
        /// <remarks/>
        public void BuscarAeropuertoAsync(string codigo, object userState) {
            if ((this.BuscarAeropuertoOperationCompleted == null)) {
                this.BuscarAeropuertoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarAeropuertoOperationCompleted);
            }
            this.InvokeAsync("BuscarAeropuerto", new object[] {
                        codigo}, this.BuscarAeropuertoOperationCompleted, userState);
        }
        
        private void OnBuscarAeropuertoOperationCompleted(object arg) {
            if ((this.BuscarAeropuertoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarAeropuertoCompleted(this, new BuscarAeropuertoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarAeropuerto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Aeropuerto[] ListarAeropuerto() {
            object[] results = this.Invoke("ListarAeropuerto", new object[0]);
            return ((Aeropuerto[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAeropuertoAsync() {
            this.ListarAeropuertoAsync(null);
        }
        
        /// <remarks/>
        public void ListarAeropuertoAsync(object userState) {
            if ((this.ListarAeropuertoOperationCompleted == null)) {
                this.ListarAeropuertoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAeropuertoOperationCompleted);
            }
            this.InvokeAsync("ListarAeropuerto", new object[0], this.ListarAeropuertoOperationCompleted, userState);
        }
        
        private void OnListarAeropuertoOperationCompleted(object arg) {
            if ((this.ListarAeropuertoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAeropuertoCompleted(this, new ListarAeropuertoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaAeropuerto", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaAeropuerto(Aeropuerto aero) {
            this.Invoke("BajaAeropuerto", new object[] {
                        aero});
        }
        
        /// <remarks/>
        public void BajaAeropuertoAsync(Aeropuerto aero) {
            this.BajaAeropuertoAsync(aero, null);
        }
        
        /// <remarks/>
        public void BajaAeropuertoAsync(Aeropuerto aero, object userState) {
            if ((this.BajaAeropuertoOperationCompleted == null)) {
                this.BajaAeropuertoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaAeropuertoOperationCompleted);
            }
            this.InvokeAsync("BajaAeropuerto", new object[] {
                        aero}, this.BajaAeropuertoOperationCompleted, userState);
        }
        
        private void OnBajaAeropuertoOperationCompleted(object arg) {
            if ((this.BajaAeropuertoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaAeropuertoCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarAero", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarAero(Aeropuerto aerom) {
            this.Invoke("ModificarAero", new object[] {
                        aerom});
        }
        
        /// <remarks/>
        public void ModificarAeroAsync(Aeropuerto aerom) {
            this.ModificarAeroAsync(aerom, null);
        }
        
        /// <remarks/>
        public void ModificarAeroAsync(Aeropuerto aerom, object userState) {
            if ((this.ModificarAeroOperationCompleted == null)) {
                this.ModificarAeroOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarAeroOperationCompleted);
            }
            this.InvokeAsync("ModificarAero", new object[] {
                        aerom}, this.ModificarAeroOperationCompleted, userState);
        }
        
        private void OnModificarAeroOperationCompleted(object arg) {
            if ((this.ModificarAeroCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarAeroCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarAeropuertoCiudadPartida", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Aeropuerto[] ListarAeropuertoCiudadPartida() {
            object[] results = this.Invoke("ListarAeropuertoCiudadPartida", new object[0]);
            return ((Aeropuerto[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarAeropuertoCiudadPartidaAsync() {
            this.ListarAeropuertoCiudadPartidaAsync(null);
        }
        
        /// <remarks/>
        public void ListarAeropuertoCiudadPartidaAsync(object userState) {
            if ((this.ListarAeropuertoCiudadPartidaOperationCompleted == null)) {
                this.ListarAeropuertoCiudadPartidaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarAeropuertoCiudadPartidaOperationCompleted);
            }
            this.InvokeAsync("ListarAeropuertoCiudadPartida", new object[0], this.ListarAeropuertoCiudadPartidaOperationCompleted, userState);
        }
        
        private void OnListarAeropuertoCiudadPartidaOperationCompleted(object arg) {
            if ((this.ListarAeropuertoCiudadPartidaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarAeropuertoCiudadPartidaCompleted(this, new ListarAeropuertoCiudadPartidaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaLineas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaLineas(LineasAereas lineas) {
            this.Invoke("AltaLineas", new object[] {
                        lineas});
        }
        
        /// <remarks/>
        public void AltaLineasAsync(LineasAereas lineas) {
            this.AltaLineasAsync(lineas, null);
        }
        
        /// <remarks/>
        public void AltaLineasAsync(LineasAereas lineas, object userState) {
            if ((this.AltaLineasOperationCompleted == null)) {
                this.AltaLineasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaLineasOperationCompleted);
            }
            this.InvokeAsync("AltaLineas", new object[] {
                        lineas}, this.AltaLineasOperationCompleted, userState);
        }
        
        private void OnAltaLineasOperationCompleted(object arg) {
            if ((this.AltaLineasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaLineasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarLineas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LineasAereas BuscarLineas(string sigla) {
            object[] results = this.Invoke("BuscarLineas", new object[] {
                        sigla});
            return ((LineasAereas)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarLineasAsync(string sigla) {
            this.BuscarLineasAsync(sigla, null);
        }
        
        /// <remarks/>
        public void BuscarLineasAsync(string sigla, object userState) {
            if ((this.BuscarLineasOperationCompleted == null)) {
                this.BuscarLineasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarLineasOperationCompleted);
            }
            this.InvokeAsync("BuscarLineas", new object[] {
                        sigla}, this.BuscarLineasOperationCompleted, userState);
        }
        
        private void OnBuscarLineasOperationCompleted(object arg) {
            if ((this.BuscarLineasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarLineasCompleted(this, new BuscarLineasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarLineas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public LineasAereas[] ListarLineas() {
            object[] results = this.Invoke("ListarLineas", new object[0]);
            return ((LineasAereas[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarLineasAsync() {
            this.ListarLineasAsync(null);
        }
        
        /// <remarks/>
        public void ListarLineasAsync(object userState) {
            if ((this.ListarLineasOperationCompleted == null)) {
                this.ListarLineasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarLineasOperationCompleted);
            }
            this.InvokeAsync("ListarLineas", new object[0], this.ListarLineasOperationCompleted, userState);
        }
        
        private void OnListarLineasOperationCompleted(object arg) {
            if ((this.ListarLineasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarLineasCompleted(this, new ListarLineasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaLineas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaLineas(LineasAereas linea) {
            this.Invoke("BajaLineas", new object[] {
                        linea});
        }
        
        /// <remarks/>
        public void BajaLineasAsync(LineasAereas linea) {
            this.BajaLineasAsync(linea, null);
        }
        
        /// <remarks/>
        public void BajaLineasAsync(LineasAereas linea, object userState) {
            if ((this.BajaLineasOperationCompleted == null)) {
                this.BajaLineasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaLineasOperationCompleted);
            }
            this.InvokeAsync("BajaLineas", new object[] {
                        linea}, this.BajaLineasOperationCompleted, userState);
        }
        
        private void OnBajaLineasOperationCompleted(object arg) {
            if ((this.BajaLineasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaLineasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarLineas", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarLineas(LineasAereas lineam) {
            this.Invoke("ModificarLineas", new object[] {
                        lineam});
        }
        
        /// <remarks/>
        public void ModificarLineasAsync(LineasAereas lineam) {
            this.ModificarLineasAsync(lineam, null);
        }
        
        /// <remarks/>
        public void ModificarLineasAsync(LineasAereas lineam, object userState) {
            if ((this.ModificarLineasOperationCompleted == null)) {
                this.ModificarLineasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarLineasOperationCompleted);
            }
            this.InvokeAsync("ModificarLineas", new object[] {
                        lineam}, this.ModificarLineasOperationCompleted, userState);
        }
        
        private void OnModificarLineasOperationCompleted(object arg) {
            if ((this.ModificarLineasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarLineasCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaVuelos", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaVuelos(Vuelos vuelo) {
            this.Invoke("AltaVuelos", new object[] {
                        vuelo});
        }
        
        /// <remarks/>
        public void AltaVuelosAsync(Vuelos vuelo) {
            this.AltaVuelosAsync(vuelo, null);
        }
        
        /// <remarks/>
        public void AltaVuelosAsync(Vuelos vuelo, object userState) {
            if ((this.AltaVuelosOperationCompleted == null)) {
                this.AltaVuelosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaVuelosOperationCompleted);
            }
            this.InvokeAsync("AltaVuelos", new object[] {
                        vuelo}, this.AltaVuelosOperationCompleted, userState);
        }
        
        private void OnAltaVuelosOperationCompleted(object arg) {
            if ((this.AltaVuelosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaVuelosCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarVuelo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vuelos BuscarVuelo(string codigo) {
            object[] results = this.Invoke("BuscarVuelo", new object[] {
                        codigo});
            return ((Vuelos)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarVueloAsync(string codigo) {
            this.BuscarVueloAsync(codigo, null);
        }
        
        /// <remarks/>
        public void BuscarVueloAsync(string codigo, object userState) {
            if ((this.BuscarVueloOperationCompleted == null)) {
                this.BuscarVueloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarVueloOperationCompleted);
            }
            this.InvokeAsync("BuscarVuelo", new object[] {
                        codigo}, this.BuscarVueloOperationCompleted, userState);
        }
        
        private void OnBuscarVueloOperationCompleted(object arg) {
            if ((this.BuscarVueloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarVueloCompleted(this, new BuscarVueloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListarVuelo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vuelos[] ListarVuelo() {
            object[] results = this.Invoke("ListarVuelo", new object[0]);
            return ((Vuelos[])(results[0]));
        }
        
        /// <remarks/>
        public void ListarVueloAsync() {
            this.ListarVueloAsync(null);
        }
        
        /// <remarks/>
        public void ListarVueloAsync(object userState) {
            if ((this.ListarVueloOperationCompleted == null)) {
                this.ListarVueloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListarVueloOperationCompleted);
            }
            this.InvokeAsync("ListarVuelo", new object[0], this.ListarVueloOperationCompleted, userState);
        }
        
        private void OnListarVueloOperationCompleted(object arg) {
            if ((this.ListarVueloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListarVueloCompleted(this, new ListarVueloCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaVuelo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaVuelo(Vuelos vuelob) {
            this.Invoke("BajaVuelo", new object[] {
                        vuelob});
        }
        
        /// <remarks/>
        public void BajaVueloAsync(Vuelos vuelob) {
            this.BajaVueloAsync(vuelob, null);
        }
        
        /// <remarks/>
        public void BajaVueloAsync(Vuelos vuelob, object userState) {
            if ((this.BajaVueloOperationCompleted == null)) {
                this.BajaVueloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaVueloOperationCompleted);
            }
            this.InvokeAsync("BajaVuelo", new object[] {
                        vuelob}, this.BajaVueloOperationCompleted, userState);
        }
        
        private void OnBajaVueloOperationCompleted(object arg) {
            if ((this.BajaVueloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaVueloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarVuelo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarVuelo(Vuelos vuelom) {
            this.Invoke("ModificarVuelo", new object[] {
                        vuelom});
        }
        
        /// <remarks/>
        public void ModificarVueloAsync(Vuelos vuelom) {
            this.ModificarVueloAsync(vuelom, null);
        }
        
        /// <remarks/>
        public void ModificarVueloAsync(Vuelos vuelom, object userState) {
            if ((this.ModificarVueloOperationCompleted == null)) {
                this.ModificarVueloOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarVueloOperationCompleted);
            }
            this.InvokeAsync("ModificarVuelo", new object[] {
                        vuelom}, this.ModificarVueloOperationCompleted, userState);
        }
        
        private void OnModificarVueloOperationCompleted(object arg) {
            if ((this.ModificarVueloCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarVueloCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Reserva", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void Reserva([System.Xml.Serialization.XmlElementAttribute("reserva")] Vuelos reserva1) {
            this.Invoke("Reserva", new object[] {
                        reserva1});
        }
        
        /// <remarks/>
        public void ReservaAsync(Vuelos reserva1) {
            this.ReservaAsync(reserva1, null);
        }
        
        /// <remarks/>
        public void ReservaAsync(Vuelos reserva1, object userState) {
            if ((this.ReservaOperationCompleted == null)) {
                this.ReservaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnReservaOperationCompleted);
            }
            this.InvokeAsync("Reserva", new object[] {
                        reserva1}, this.ReservaOperationCompleted, userState);
        }
        
        private void OnReservaOperationCompleted(object arg) {
            if ((this.ReservaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ReservaCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ListAeroPartidados", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Vuelos[] ListAeroPartidados(string Ae) {
            object[] results = this.Invoke("ListAeroPartidados", new object[] {
                        Ae});
            return ((Vuelos[])(results[0]));
        }
        
        /// <remarks/>
        public void ListAeroPartidadosAsync(string Ae) {
            this.ListAeroPartidadosAsync(Ae, null);
        }
        
        /// <remarks/>
        public void ListAeroPartidadosAsync(string Ae, object userState) {
            if ((this.ListAeroPartidadosOperationCompleted == null)) {
                this.ListAeroPartidadosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListAeroPartidadosOperationCompleted);
            }
            this.InvokeAsync("ListAeroPartidados", new object[] {
                        Ae}, this.ListAeroPartidadosOperationCompleted, userState);
        }
        
        private void OnListAeroPartidadosOperationCompleted(object arg) {
            if ((this.ListAeroPartidadosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListAeroPartidadosCompleted(this, new ListAeroPartidadosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Logueo", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuarios Logueo(string pUsu, string pPass) {
            object[] results = this.Invoke("Logueo", new object[] {
                        pUsu,
                        pPass});
            return ((Usuarios)(results[0]));
        }
        
        /// <remarks/>
        public void LogueoAsync(string pUsu, string pPass) {
            this.LogueoAsync(pUsu, pPass, null);
        }
        
        /// <remarks/>
        public void LogueoAsync(string pUsu, string pPass, object userState) {
            if ((this.LogueoOperationCompleted == null)) {
                this.LogueoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnLogueoOperationCompleted);
            }
            this.InvokeAsync("Logueo", new object[] {
                        pUsu,
                        pPass}, this.LogueoOperationCompleted, userState);
        }
        
        private void OnLogueoOperationCompleted(object arg) {
            if ((this.LogueoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.LogueoCompleted(this, new LogueoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/AltaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void AltaUsuario(Usuarios usu) {
            this.Invoke("AltaUsuario", new object[] {
                        usu});
        }
        
        /// <remarks/>
        public void AltaUsuarioAsync(Usuarios usu) {
            this.AltaUsuarioAsync(usu, null);
        }
        
        /// <remarks/>
        public void AltaUsuarioAsync(Usuarios usu, object userState) {
            if ((this.AltaUsuarioOperationCompleted == null)) {
                this.AltaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnAltaUsuarioOperationCompleted);
            }
            this.InvokeAsync("AltaUsuario", new object[] {
                        usu}, this.AltaUsuarioOperationCompleted, userState);
        }
        
        private void OnAltaUsuarioOperationCompleted(object arg) {
            if ((this.AltaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.AltaUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BajaUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void BajaUsuario(Usuarios usub) {
            this.Invoke("BajaUsuario", new object[] {
                        usub});
        }
        
        /// <remarks/>
        public void BajaUsuarioAsync(Usuarios usub) {
            this.BajaUsuarioAsync(usub, null);
        }
        
        /// <remarks/>
        public void BajaUsuarioAsync(Usuarios usub, object userState) {
            if ((this.BajaUsuarioOperationCompleted == null)) {
                this.BajaUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBajaUsuarioOperationCompleted);
            }
            this.InvokeAsync("BajaUsuario", new object[] {
                        usub}, this.BajaUsuarioOperationCompleted, userState);
        }
        
        private void OnBajaUsuarioOperationCompleted(object arg) {
            if ((this.BajaUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BajaUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ModificarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void ModificarUsuario(Usuarios usum) {
            this.Invoke("ModificarUsuario", new object[] {
                        usum});
        }
        
        /// <remarks/>
        public void ModificarUsuarioAsync(Usuarios usum) {
            this.ModificarUsuarioAsync(usum, null);
        }
        
        /// <remarks/>
        public void ModificarUsuarioAsync(Usuarios usum, object userState) {
            if ((this.ModificarUsuarioOperationCompleted == null)) {
                this.ModificarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnModificarUsuarioOperationCompleted);
            }
            this.InvokeAsync("ModificarUsuario", new object[] {
                        usum}, this.ModificarUsuarioOperationCompleted, userState);
        }
        
        private void OnModificarUsuarioOperationCompleted(object arg) {
            if ((this.ModificarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ModificarUsuarioCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/BuscarUsuario", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public Usuarios BuscarUsuario(int ndoc) {
            object[] results = this.Invoke("BuscarUsuario", new object[] {
                        ndoc});
            return ((Usuarios)(results[0]));
        }
        
        /// <remarks/>
        public void BuscarUsuarioAsync(int ndoc) {
            this.BuscarUsuarioAsync(ndoc, null);
        }
        
        /// <remarks/>
        public void BuscarUsuarioAsync(int ndoc, object userState) {
            if ((this.BuscarUsuarioOperationCompleted == null)) {
                this.BuscarUsuarioOperationCompleted = new System.Threading.SendOrPostCallback(this.OnBuscarUsuarioOperationCompleted);
            }
            this.InvokeAsync("BuscarUsuario", new object[] {
                        ndoc}, this.BuscarUsuarioOperationCompleted, userState);
        }
        
        private void OnBuscarUsuarioOperationCompleted(object arg) {
            if ((this.BuscarUsuarioCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.BuscarUsuarioCompleted(this, new BuscarUsuarioCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/Listavuelosxml", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public System.Xml.XmlNode Listavuelosxml(Cliente cli) {
            object[] results = this.Invoke("Listavuelosxml", new object[] {
                        cli});
            return ((System.Xml.XmlNode)(results[0]));
        }
        
        /// <remarks/>
        public void ListavuelosxmlAsync(Cliente cli) {
            this.ListavuelosxmlAsync(cli, null);
        }
        
        /// <remarks/>
        public void ListavuelosxmlAsync(Cliente cli, object userState) {
            if ((this.ListavuelosxmlOperationCompleted == null)) {
                this.ListavuelosxmlOperationCompleted = new System.Threading.SendOrPostCallback(this.OnListavuelosxmlOperationCompleted);
            }
            this.InvokeAsync("Listavuelosxml", new object[] {
                        cli}, this.ListavuelosxmlOperationCompleted, userState);
        }
        
        private void OnListavuelosxmlOperationCompleted(object arg) {
            if ((this.ListavuelosxmlCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ListavuelosxmlCompleted(this, new ListavuelosxmlCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Cliente : Usuarios {
        
        private long targetaField;
        
        /// <comentarios/>
        public long Targeta {
            get {
                return this.targetaField;
            }
            set {
                this.targetaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Administrador))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(Cliente))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Usuarios {
        
        private int ndocField;
        
        private string nomUsuField;
        
        private string usuarioField;
        
        private string contraseñaField;
        
        /// <comentarios/>
        public int Ndoc {
            get {
                return this.ndocField;
            }
            set {
                this.ndocField = value;
            }
        }
        
        /// <comentarios/>
        public string NomUsu {
            get {
                return this.nomUsuField;
            }
            set {
                this.nomUsuField = value;
            }
        }
        
        /// <comentarios/>
        public string Usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
        
        /// <comentarios/>
        public string Contraseña {
            get {
                return this.contraseñaField;
            }
            set {
                this.contraseñaField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Reservas {
        
        private Cliente unClienteField;
        
        private int asientoField;
        
        /// <comentarios/>
        public Cliente UnCliente {
            get {
                return this.unClienteField;
            }
            set {
                this.unClienteField = value;
            }
        }
        
        /// <comentarios/>
        public int Asiento {
            get {
                return this.asientoField;
            }
            set {
                this.asientoField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Vuelos {
        
        private string codVueloField;
        
        private int asientosField;
        
        private System.DateTime fechaHoraField;
        
        private LineasAereas lineaField;
        
        private Aeropuerto aeropuertosalidaField;
        
        private Aeropuerto aeropuertollegadaField;
        
        private Reservas[] reservasField;
        
        private string siglaLineaField;
        
        private string codAeropuertoSalidaField;
        
        private string codAeropuertoLlegadaField;
        
        private int cantReservasField;
        
        /// <comentarios/>
        public string CodVuelo {
            get {
                return this.codVueloField;
            }
            set {
                this.codVueloField = value;
            }
        }
        
        /// <comentarios/>
        public int Asientos {
            get {
                return this.asientosField;
            }
            set {
                this.asientosField = value;
            }
        }
        
        /// <comentarios/>
        public System.DateTime FechaHora {
            get {
                return this.fechaHoraField;
            }
            set {
                this.fechaHoraField = value;
            }
        }
        
        /// <comentarios/>
        public LineasAereas Linea {
            get {
                return this.lineaField;
            }
            set {
                this.lineaField = value;
            }
        }
        
        /// <comentarios/>
        public Aeropuerto Aeropuertosalida {
            get {
                return this.aeropuertosalidaField;
            }
            set {
                this.aeropuertosalidaField = value;
            }
        }
        
        /// <comentarios/>
        public Aeropuerto Aeropuertollegada {
            get {
                return this.aeropuertollegadaField;
            }
            set {
                this.aeropuertollegadaField = value;
            }
        }
        
        /// <comentarios/>
        public Reservas[] Reservas {
            get {
                return this.reservasField;
            }
            set {
                this.reservasField = value;
            }
        }
        
        /// <comentarios/>
        public string SiglaLinea {
            get {
                return this.siglaLineaField;
            }
            set {
                this.siglaLineaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodAeropuertoSalida {
            get {
                return this.codAeropuertoSalidaField;
            }
            set {
                this.codAeropuertoSalidaField = value;
            }
        }
        
        /// <comentarios/>
        public string CodAeropuertoLlegada {
            get {
                return this.codAeropuertoLlegadaField;
            }
            set {
                this.codAeropuertoLlegadaField = value;
            }
        }
        
        /// <comentarios/>
        public int CantReservas {
            get {
                return this.cantReservasField;
            }
            set {
                this.cantReservasField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class LineasAereas {
        
        private string siglaLineaField;
        
        private string dirLineaField;
        
        private TelLineas[] telefonosField;
        
        /// <comentarios/>
        public string SiglaLinea {
            get {
                return this.siglaLineaField;
            }
            set {
                this.siglaLineaField = value;
            }
        }
        
        /// <comentarios/>
        public string DirLinea {
            get {
                return this.dirLineaField;
            }
            set {
                this.dirLineaField = value;
            }
        }
        
        /// <comentarios/>
        public TelLineas[] Telefonos {
            get {
                return this.telefonosField;
            }
            set {
                this.telefonosField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class TelLineas {
        
        private string unTelField;
        
        /// <comentarios/>
        public string UnTel {
            get {
                return this.unTelField;
            }
            set {
                this.unTelField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Aeropuerto {
        
        private string codAeroField;
        
        private string nomAeroField;
        
        private string ciudadField;
        
        /// <comentarios/>
        public string CodAero {
            get {
                return this.codAeroField;
            }
            set {
                this.codAeroField = value;
            }
        }
        
        /// <comentarios/>
        public string NomAero {
            get {
                return this.nomAeroField;
            }
            set {
                this.nomAeroField = value;
            }
        }
        
        /// <comentarios/>
        public string Ciudad {
            get {
                return this.ciudadField;
            }
            set {
                this.ciudadField = value;
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://tempuri.org/")]
    public partial class Administrador : Usuarios {
        
        private bool generavuelosField;
        
        /// <comentarios/>
        public bool Generavuelos {
            get {
                return this.generavuelosField;
            }
            set {
                this.generavuelosField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SerializarClienteCompletedEventHandler(object sender, SerializarClienteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SerializarClienteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SerializarClienteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Cliente Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Cliente)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SerializarAdminCompletedEventHandler(object sender, SerializarAdminCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SerializarAdminCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SerializarAdminCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Administrador Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Administrador)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AltaAeropuertoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BuscarAeropuertoCompletedEventHandler(object sender, BuscarAeropuertoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarAeropuertoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarAeropuertoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Aeropuerto Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Aeropuerto)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarAeropuertoCompletedEventHandler(object sender, ListarAeropuertoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAeropuertoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAeropuertoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Aeropuerto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Aeropuerto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BajaAeropuertoCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModificarAeroCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarAeropuertoCiudadPartidaCompletedEventHandler(object sender, ListarAeropuertoCiudadPartidaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarAeropuertoCiudadPartidaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarAeropuertoCiudadPartidaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Aeropuerto[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Aeropuerto[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AltaLineasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BuscarLineasCompletedEventHandler(object sender, BuscarLineasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarLineasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarLineasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LineasAereas Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LineasAereas)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarLineasCompletedEventHandler(object sender, ListarLineasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarLineasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarLineasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public LineasAereas[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((LineasAereas[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BajaLineasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModificarLineasCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AltaVuelosCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BuscarVueloCompletedEventHandler(object sender, BuscarVueloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarVueloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarVueloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vuelos Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vuelos)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListarVueloCompletedEventHandler(object sender, ListarVueloCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListarVueloCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListarVueloCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vuelos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vuelos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BajaVueloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModificarVueloCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ReservaCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListAeroPartidadosCompletedEventHandler(object sender, ListAeroPartidadosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListAeroPartidadosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListAeroPartidadosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Vuelos[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Vuelos[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void LogueoCompletedEventHandler(object sender, LogueoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class LogueoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal LogueoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuarios Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuarios)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void AltaUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BajaUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ModificarUsuarioCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void BuscarUsuarioCompletedEventHandler(object sender, BuscarUsuarioCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class BuscarUsuarioCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal BuscarUsuarioCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public Usuarios Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((Usuarios)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void ListavuelosxmlCompletedEventHandler(object sender, ListavuelosxmlCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ListavuelosxmlCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ListavuelosxmlCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public System.Xml.XmlNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((System.Xml.XmlNode)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591